version: '2'
services:
    scheduler-app:
        image: scheduler
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${coolybot.registry.password}@coolybot-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${coolybot.registry.password}@coolybot-registry:8761/config
            - SPRING_DATA_MONGODB_URI=mongodb://scheduler-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=scheduler
            - COOLYBOT_SLEEP=30 # gives time for the Coolybot Registry to boot before the application
            - SPRING_DATA_JEST_URI=http://scheduler-elasticsearch:9200
    scheduler-mongodb:
        extends:
            file: mongodb.yml
            service: scheduler-mongodb
    scheduler-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: scheduler-elasticsearch
    coolybot-registry:
        extends:
            file: coolybot-registry.yml
            service: coolybot-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
